
title:                Stacks API
tagline:              Simple. Fast. Awesome.
url:                  "http://localhost:8080"
baseurl:              ""

safe:                 true      # enable safe mode to match github pages
permalink:           	pretty    # make prettty link
relative_permalinks: 	true


# Setup

# Assets
#
# We specify the directory for Jekyll so we can use @imports.

sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Isaiah Carew
  url:               http://yourhead.com

# Custom vars
version:             7
repo:                https://github.com/yourhead/StacksAPI
highlighter: 		 pygments
github: 		     [Repository metadata]

# Collections
collections:
  properties:
      output:	true
  controls:
      output:	true
  

#defaults
defaults:
  - scope:
      path: ""
      type: "controls"
    values:
      layout: "control"