
url:                  "http://localhost:8080"
baseurl:              ""
reloader:             YES


# Everything below here should be identical in both local and github setups

safe:                true      # enable safe mode to match github pages
permalink:           pretty    # make prettty link
relative_permalinks: true
highlighter:         pygments


title:               Stacks API
tagline:             Simple. Fast. Awesome.
version:             6
stacksVersion:       2.5
author:
  name:              YourHead Software
  url:               http://yourhead.com



# sass needs to be be setup for some lame reason
sass:
  sass_dir:          _sass
  style:             :compressed


# Collections -- seriously, couldn't this just the be default
collections:
  keys:
      output: true
  controls:
      output: true
  

# Default layouts for various things
defaults:
  - scope:
      path: ""
      type: "controls"
    values:
      layout: "control"
  - scope:
      path: ""
      type: "keys"
    values:
      layout: "key"


